version: "3.7"
services:
  filemon:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    env_file:
      - .env
  db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=filemon
    ports:
      - '5432:5432'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --reload
    tty: true
    volumes:
      - ./:/src
    env_file:
      - .env
    ports:
      - "8000:8000"
