name: "Python"

on: [ push ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: "Python"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Create env file'
        run: touch .env

      - name: Build the stack
        run: docker-compose up -d filemon

      - name: flake8
        run: docker-compose run --rm filemon flake8 .

      - name: mypy
        run: docker-compose run --rm filemon mypy .

      - name: pytest
        run: docker-compose run --rm filemon pytest .

      - name: Stop containers
        if: always()
        run: docker-compose down
